# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ef56dea3a2ed7f592f7d9823d3cb44cfe9ee0667c5671e264f03dc3d975cb275bd864b47e9c5f45c174071c63ec43adfda531105fd3332f2f9aadf2374406e7

test:
  secret_key_base: dd1df647380a4d17fc9b3053c32940f88d2e977418e7fe34e72150fa5b6b090f2d96bc46020003feb11f8d901a5a1a5143cd1b0e302f41610e85ac0a0826d7b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
